name: lighttask_prod

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${LIGHTTASK_CONFIG__DB__USER}
      POSTGRES_PASSWORD: ${LIGHTTASK_CONFIG__DB__PASSWORD}
      POSTGRES_DB: ${LIGHTTASK_CONFIG__DB__NAME}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${LIGHTTASK_CONFIG__DB__USER} -d ${LIGHTTASK_CONFIG__DB__NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    image: ghcr.io/${IMAGE_REPO_OWNER}/lighttask-backend:main
    restart: always
    env_file: .env
    volumes:
      - ./certs:/app/certs:ro
    environment:
      - LIGHTTASK_CONFIG__DB__HOST=db
      - LIGHTTASK_CONFIG__RUN__HOST=0.0.0.0
      - LIGHTTASK_CONFIG__RUN__PORT=8000
      - LIGHTTASK_CONFIG__RUN__CORS_ORIGINS=["https://do-coop.ru","https://www.do-coop.ru","https://144.31.201.48"]
      - LIGHTTASK_CONFIG__INVITE__BASE_URL=https://do-coop.ru/invite
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - frontend-api
      - backend-db
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 400M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: ghcr.io/${IMAGE_REPO_OWNER}/lighttask-frontend:main
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot_etc:/etc/letsencrypt:ro
      - certbot_var:/var/www/certbot:ro
    depends_on:
      - backend
    networks:
      - frontend-api
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 150M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    networks:
      frontend-api:
      backend-db:

volumes:
  postgres_data_prod:
  certbot_etc:
  certbot_var:
