name: Deploy to Production

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_REPO_OWNER: ilm1n
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend/light_task
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO_OWNER }}/lighttask-backend:main
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO_OWNER }}/lighttask-backend:${{ steps.vars.outputs.sha_short }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/light-task-frontend
          file: ./frontend/light-task-frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO_OWNER }}/lighttask-frontend:main
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO_OWNER }}/lighttask-frontend:${{ steps.vars.outputs.sha_short }}

    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout config
        uses: actions/checkout@v4

      - name: Create config and certs
        env:
          PROD_ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
          JWT_PRIVATE: ${{ secrets.JWT_PRIVATE_KEY }}
          JWT_PUBLIC: ${{ secrets.JWT_PUBLIC_KEY }}
          TAG: ${{ needs.build-and-push.outputs.sha_short }}
        run: |
          printf "%s" "$PROD_ENV_FILE" > .env.prod
          echo "IMAGE_REPO_OWNER=${{ env.IMAGE_REPO_OWNER }}" >> .env.prod
          echo "IMAGE_TAG=$TAG" >> .env.prod
            
          mkdir -p certs
          printf "%s" "$JWT_PRIVATE" > certs/jwt-private.pem
          printf "%s" "$JWT_PUBLIC" > certs/jwt-public.pem

      - name: Copy files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "docker-compose.prod.yml,.env.prod,Caddyfile,certs/"
          target: "/home/${{ secrets.VPS_USER }}/app"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd ~/app
            mv .env.prod .env
            
            chmod 600 certs/*.pem
            
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --force-recreate --remove-orphans
            docker image prune -af

  cleanup:
    name: Cleanup Old Images
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Old Backend Images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'lighttask-backend'
          package-type: 'container'
          min-versions-to-keep: 2
          delete-only-untagged-versions: 'false'

      - name: Delete Old Frontend Images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'lighttask-frontend'
          package-type: 'container'
          min-versions-to-keep: 2
          delete-only-untagged-versions: 'false'